-- Generated from src/data/places.ts — 46 places
-- Run after 004_places.sql

insert into public.places (
  id, name, city, region, category, tags,
  distance_label, leash_info, dog_friendly_notes, why_dogs_love_it, best_time,
  energy_level, address_label, lat, lng, featured, popular_now,
  image_url, image_alt, image_tone, is_active
) values
(
  'dog-beach-ocean-beach',
  'Dog Beach, Ocean Beach',
  'San Diego',
  'San Diego',
  'Beach',
  '{"off-leash","water","social"}',
  '1.4 mi',
  'Off-leash',
  'Dedicated off-leash beach at the north end of Ocean Beach.',
  'Wave chasing, sand rolls, and a packed social scene every morning.',
  'Sunrise or weekday mornings',
  'High',
  '5156 W Point Loma Blvd',
  32.7551,
  -117.2534,
  true,
  true,
  '/sample-images/coastal.jpg',
  'Dog Beach, Ocean Beach — beach spot',
  'coastal',
  true
),
(
  'coronado-dog-beach',
  'Coronado Dog Beach',
  'Coronado',
  'San Diego',
  'Beach',
  '{"off-leash","water","flat-sand"}',
  '6.8 mi',
  'Off-leash',
  'Wide flat beach at the north end of Coronado near the naval base.',
  'Gentle surf and room to sprint without crowds mid-week.',
  'Early morning before parking fills',
  'High',
  null,
  32.6917,
  -117.1831,
  true,
  false,
  '/sample-images/beach.jpg',
  'Coronado Dog Beach — beach spot',
  'coastal',
  true
),
(
  'del-mar-dog-beach',
  'Del Mar Dog Beach',
  'Del Mar',
  'San Diego',
  'Beach',
  '{"off-leash","water","scenic"}',
  '18 mi',
  'Off-leash',
  'North of 29th Street in Del Mar — one of the best-known SD dog beaches.',
  'Soft sand, consistent surf, and post-walk patio stops nearby.',
  'Late afternoon · best window today',
  'High',
  null,
  32.9645,
  -117.2653,
  true,
  true,
  '/sample-images/coastal.jpg',
  'Del Mar Dog Beach — beach spot',
  'coastal',
  true
),
(
  'fiesta-island',
  'Fiesta Island',
  'San Diego',
  'San Diego',
  'Beach',
  '{"off-leash","water","flat"}',
  '5.2 mi',
  'Off-leash',
  'Fully off-leash island in Mission Bay with calm water edges.',
  'Shallow bay water, flat running loops, and breeze on hot days.',
  'Weekday mornings',
  'Moderate',
  null,
  32.7712,
  -117.2189,
  false,
  false,
  '/sample-images/beach.jpg',
  'Fiesta Island — beach spot',
  'coastal',
  true
),
(
  'la-jolla-shores',
  'La Jolla Shores Beach',
  'La Jolla',
  'San Diego',
  'Beach',
  '{"on-leash","water","family"}',
  '9.1 mi',
  'On-leash',
  'Dogs allowed on-leash before 9am and after 4pm in summer.',
  'Gentle waves and a long flat strand for sniff-heavy walks.',
  'Before 9am',
  'Moderate',
  null,
  32.8584,
  -117.2573,
  false,
  false,
  '/sample-images/coastal.jpg',
  'La Jolla Shores Beach — beach spot',
  'coastal',
  true
),
(
  'mission-bay',
  'Mission Bay',
  'San Diego',
  'San Diego',
  'Beach',
  '{"on-leash","water","bay"}',
  '5.5 mi',
  'On-leash',
  'Shoreline paths and grassy park edges around Mission Bay.',
  'Flat bay walks, breeze, and room to sniff without steep hills.',
  'Sunset shoreline loop',
  'Moderate',
  null,
  32.7648,
  -117.2268,
  false,
  false,
  '/sample-images/coastal.jpg',
  'Mission Bay — beach spot',
  'coastal',
  true
),
(
  'pacific-beach',
  'Pacific Beach',
  'San Diego',
  'San Diego',
  'Beach',
  '{"on-leash","water","boardwalk"}',
  '7.2 mi',
  'On-leash',
  'Boardwalk and beach strand — busy on weekends, calmer at sunrise.',
  'Boardwalk energy, sand, and a classic San Diego beach day.',
  'Early morning before crowds',
  'Moderate',
  null,
  32.799,
  -117.254,
  false,
  false,
  '/sample-images/coastal.jpg',
  'Pacific Beach — beach spot',
  'coastal',
  true
),
(
  'cardiff-dog-beach',
  'Cardiff Dog Beach',
  'Encinitas',
  'San Diego',
  'Beach',
  '{"off-leash","water","north-county"}',
  '24 mi',
  'Off-leash',
  'North County off-leash stretch at the south end of Cardiff State Beach.',
  'Wide sand, steady surf, and a north-county change of pace.',
  'Weekday mornings',
  'High',
  null,
  33.0102,
  -117.2794,
  false,
  false,
  '/sample-images/beach.jpg',
  'Cardiff Dog Beach — beach spot',
  'coastal',
  true
),
(
  'huntington-dog-beach',
  'Huntington Dog Beach',
  'Huntington Beach',
  'Orange County',
  'Beach',
  '{"off-leash","water","iconic"}',
  '88 mi',
  'Off-leash',
  '1.5 miles of off-leash beach between Seapoint and 21st Street.',
  'Endless sand, surf, and the most famous OC dog beach scene.',
  'Weekday mornings to beat traffic',
  'High',
  null,
  33.6595,
  -118.0012,
  true,
  true,
  '/sample-images/coastal.jpg',
  'Huntington Dog Beach — beach spot',
  'coastal',
  true
),
(
  'newport-dog-beach',
  'Newport Beach Dog Zone',
  'Newport Beach',
  'Orange County',
  'Beach',
  '{"on-leash","water","harbor"}',
  '82 mi',
  'On-leash',
  'Dogs welcome on-leash at specified beach zones and harbor paths.',
  'Harbor smells, sailboats, and a change of scenery from SD beaches.',
  'Morning harbor walk',
  'Low',
  null,
  33.6189,
  -117.9298,
  false,
  false,
  '/sample-images/beach.jpg',
  'Newport Beach Dog Zone — beach spot',
  'coastal',
  true
),
(
  'torrey-pines',
  'Torrey Pines State Reserve',
  'La Jolla',
  'San Diego',
  'Trail',
  '{"on-leash","coastal","views"}',
  '12 mi',
  'On-leash',
  'Dogs on-leash on designated trails — avoid fragile habitat areas.',
  'Ocean views, sage scrub smells, and a real workout on the switchbacks.',
  'Weekday sunrise',
  'High',
  null,
  32.9201,
  -117.2533,
  true,
  false,
  '/sample-images/park.jpg',
  'Torrey Pines State Reserve — trail spot',
  'forest',
  true
),
(
  'cowles-mountain',
  'Cowles Mountain Trail',
  'San Diego',
  'San Diego',
  'Trail',
  '{"on-leash","summit","workout"}',
  '8.4 mi',
  'On-leash',
  'Popular Mission Trails summit — dogs on-leash, bring water.',
  'Summit views and the satisfaction of a steep climb together.',
  'Early morning before heat',
  'High',
  null,
  32.8129,
  -117.0312,
  true,
  false,
  '/sample-images/park.jpg',
  'Cowles Mountain Trail — trail spot',
  'forest',
  true
),
(
  'iron-mountain',
  'Iron Mountain Trail',
  'Poway',
  'San Diego',
  'Trail',
  '{"on-leash","wildflowers","moderate"}',
  '22 mi',
  'On-leash',
  'Well-marked loop with seasonal wildflowers in spring.',
  'Shaded sections, varied terrain, and fewer crowds than Cowles.',
  'Spring mornings',
  'Moderate',
  null,
  33.0184,
  -116.9678,
  false,
  false,
  '/sample-images/trail.jpg',
  'Iron Mountain Trail — trail spot',
  'forest',
  true
),
(
  'mission-trails-kwaay-paay',
  'Mission Trails — Kwaay Paay Peak',
  'San Diego',
  'San Diego',
  'Trail',
  '{"on-leash","local","moderate"}',
  '7.6 mi',
  'On-leash',
  'Shorter summit option inside Mission Trails Regional Park.',
  'Quick elevation gain and valley views without a long drive.',
  'Sunset hike',
  'Moderate',
  null,
  32.7856,
  -117.0512,
  false,
  false,
  '/sample-images/trail.jpg',
  'Mission Trails — Kwaay Paay Peak — trail spot',
  'forest',
  true
),
(
  'lestats-coffee',
  'Lestat''s Coffee House',
  'San Diego',
  'San Diego',
  'Coffee',
  '{"patio","local","late-night"}',
  '2.1 mi',
  'Patio dogs welcome',
  'Classic SD coffee spot with outdoor seating and a neighborhood vibe.',
  'People watching, patio treats, and the buzz of Normal Heights.',
  'Morning coffee run',
  'Low',
  '3349 Adams Ave',
  32.7641,
  -117.1223,
  true,
  false,
  '/sample-images/cafe.jpg',
  'Lestat''s Coffee House — coffee spot',
  'urban',
  true
),
(
  'better-buzz-hillcrest',
  'Better Buzz Coffee — Hillcrest',
  'San Diego',
  'San Diego',
  'Coffee',
  '{"patio","busy","local"}',
  '3.0 mi',
  'Patio dogs welcome',
  'Outdoor tables on the sidewalk — keep pups leashed and close.',
  'High-energy patio scene and a short walk through Hillcrest.',
  'Weekday mid-morning',
  'Low',
  null,
  32.7489,
  -117.1667,
  false,
  true,
  '/sample-images/cafe.jpg',
  'Better Buzz Coffee — Hillcrest — coffee spot',
  'urban',
  true
),
(
  'holsem-coffee',
  'Holsem Coffee',
  'San Diego',
  'San Diego',
  'Coffee',
  '{"patio","neighborhood","pastries"}',
  '4.5 mi',
  'Patio dogs welcome',
  'South Park favorite with sidewalk seating and calm mornings.',
  'Relaxed patio hangs and a tree-lined walk to get there.',
  'Slow weekend morning',
  'Low',
  null,
  32.7298,
  -117.1298,
  false,
  false,
  '/sample-images/cafe.jpg',
  'Holsem Coffee — coffee spot',
  'urban',
  true
),
(
  'ballast-point-little-italy',
  'Ballast Point — Little Italy',
  'San Diego',
  'San Diego',
  'Brewery',
  '{"patio","beer","waterfront-nearby"}',
  '2.8 mi',
  'Patio dogs welcome',
  'Dog-friendly patio in Little Italy — busy on weekends.',
  'Patio energy, new smells, and a walk through the neighborhood after.',
  'Weekday afternoon',
  'Low',
  null,
  32.7234,
  -117.1689,
  true,
  false,
  '/sample-images/cafe.jpg',
  'Ballast Point — Little Italy — brewery spot',
  'urban',
  true
),
(
  'modern-times-flavordome',
  'Modern Times — Flavordome',
  'San Diego',
  'San Diego',
  'Brewery',
  '{"patio","beer","north-park"}',
  '3.6 mi',
  'Patio dogs welcome',
  'Large outdoor area in North Park with room for leashed pups.',
  'Open patio, other dogs around, and a fun post-walk reward.',
  'Late afternoon',
  'Low',
  null,
  32.7412,
  -117.1298,
  false,
  false,
  '/sample-images/brewery.jpg',
  'Modern Times — Flavordome — brewery spot',
  'urban',
  true
),
(
  'nates-point',
  'Nate''s Point Dog Park',
  'San Diego',
  'San Diego',
  'Dog park',
  '{"off-leash","enclosed","balboa"}',
  '3.4 mi',
  'Off-leash enclosed',
  'Large fenced off-leash area on the west side of Balboa Park.',
  'Full-speed zoomies and regulars who know every pup by name.',
  'Morning social hour',
  'High',
  null,
  32.7341,
  -117.1445,
  true,
  false,
  '/sample-images/park.jpg',
  'Nate''s Point Dog Park — dog park spot',
  'park',
  true
),
(
  'grape-street-dog-park',
  'Grape Street Dog Park',
  'San Diego',
  'San Diego',
  'Dog park',
  '{"off-leash","enclosed","south-park"}',
  '4.2 mi',
  'Off-leash enclosed',
  'Neighborhood favorite in South Park with separate small-dog area.',
  'Tight community feel and easy walk from nearby cafes.',
  'After-work play session',
  'High',
  null,
  32.7291,
  -117.1291,
  false,
  false,
  '/sample-images/dog-park.jpg',
  'Grape Street Dog Park — dog park spot',
  'park',
  true
),
(
  'dusty-rhodes',
  'Dusty Rhodes Dog Park',
  'San Diego',
  'San Diego',
  'Dog park',
  '{"off-leash","ocean-breeze","ob"}',
  '1.8 mi',
  'Off-leash enclosed',
  'Ocean-view off-leash park in Ocean Beach — can get windy.',
  'Sea breeze, sand underfoot, and a quick beach combo nearby.',
  'Morning before wind picks up',
  'High',
  null,
  32.7512,
  -117.2489,
  false,
  true,
  '/sample-images/dog-park.jpg',
  'Dusty Rhodes Dog Park — dog park spot',
  'park',
  true
),
(
  'central-bark-lake-forest',
  'Central Bark Dog Park',
  'Lake Forest',
  'Orange County',
  'Dog park',
  '{"off-leash","enclosed","large"}',
  '72 mi',
  'Off-leash enclosed',
  'Spacious OC dog park with separate areas for different sizes.',
  'Room to run and a full OC day-trip adventure vibe.',
  'Weekday mid-morning',
  'High',
  null,
  33.6467,
  -117.6891,
  false,
  false,
  '/sample-images/park.jpg',
  'Central Bark Dog Park — dog park spot',
  'park',
  true
),
(
  'balboa-park',
  'Balboa Park',
  'San Diego',
  'San Diego',
  'Park',
  '{"on-leash","cultural","wide-paths"}',
  '3.2 mi',
  'On-leash',
  'Dogs on-leash on paved paths — museums and gardens vary by rules.',
  'Endless paths, fountains, and new corners every visit.',
  'Weekday morning stroll',
  'Moderate',
  null,
  32.7341,
  -117.1446,
  true,
  false,
  '/sample-images/park.jpg',
  'Balboa Park — park spot',
  'park',
  true
),
(
  'kate-sessions',
  'Kate Sessions Memorial Park',
  'San Diego',
  'San Diego',
  'Park',
  '{"on-leash","views","sunset"}',
  '6.5 mi',
  'On-leash',
  'Grassy park on Mount Soledad with panoramic views.',
  'Open grass, sunset views, and a breezy hilltop walk.',
  'Best window today',
  'Moderate',
  null,
  32.8321,
  -117.2412,
  false,
  false,
  '/sample-images/gardens.jpg',
  'Kate Sessions Memorial Park — park spot',
  'park',
  true
),
(
  'tecolote-canyon',
  'Tecolote Canyon Natural Park',
  'San Diego',
  'San Diego',
  'Park',
  '{"on-leash","canyon","quiet"}',
  '5.8 mi',
  'On-leash',
  'Shaded canyon trails in Clairemont — cooler on hot days.',
  'Wild canyon smells and bird activity away from crowds.',
  'Cool morning',
  'Moderate',
  null,
  32.7812,
  -117.1912,
  false,
  false,
  '/sample-images/park.jpg',
  'Tecolote Canyon Natural Park — park spot',
  'park',
  true
),
(
  'balboa-rose-garden',
  'Balboa Park Rose Garden',
  'San Diego',
  'San Diego',
  'Gardens',
  '{"on-leash","flowers","seasonal"}',
  '3.2 mi',
  'On-leash',
  'Inez Grant Parker Memorial Rose Garden — peak bloom in spring.',
  'Color, fragrance, and a photogenic loop through the blooms.',
  'Spring mornings',
  'Low',
  null,
  32.7312,
  -117.1489,
  true,
  false,
  '/sample-images/park.jpg',
  'Balboa Park Rose Garden — gardens spot',
  'park',
  true
),
(
  'san-diego-botanic-garden',
  'San Diego Botanic Garden',
  'Encinitas',
  'San Diego',
  'Gardens',
  '{"on-leash","trails","coastal"}',
  '26 mi',
  'On-leash',
  'Dogs allowed on-leash on select trails — check day-of rules.',
  'Global garden zones and shaded paths on a coastal hill.',
  'Weekday visit',
  'Moderate',
  null,
  33.0512,
  -117.2812,
  false,
  false,
  '/sample-images/gardens.jpg',
  'San Diego Botanic Garden — gardens spot',
  'park',
  true
),
(
  'north-park-loop',
  'North Park Neighborhood Loop',
  'San Diego',
  'San Diego',
  'Neighborhood',
  '{"on-leash","urban","cafes"}',
  '3.5 mi',
  'On-leash',
  'Self-guided loop through 30th Street, shops, and side streets.',
  'New storefront smells, friendly neighbors, and cafe stops.',
  'Saturday morning',
  'Low',
  null,
  32.7412,
  -117.1298,
  false,
  false,
  '/sample-images/park.jpg',
  'North Park Neighborhood Loop — neighborhood spot',
  'warm',
  true
),
(
  'liberty-station',
  'Liberty Station Waterfront Walk',
  'San Diego',
  'San Diego',
  'Neighborhood',
  '{"on-leash","waterfront","flat"}',
  '4.8 mi',
  'On-leash',
  'Flat promenade through the arts district and marina paths.',
  'Harbor views, public art, and a calm flat walk for senior pups.',
  'Evening stroll',
  'Low',
  null,
  32.7267,
  -117.2145,
  false,
  false,
  '/sample-images/neighborhood.jpg',
  'Liberty Station Waterfront Walk — neighborhood spot',
  'warm',
  true
),
(
  'julian-day-trip',
  'Julian Dog-Friendly Day Trip',
  'Julian',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","apples","mountain"}',
  '62 mi',
  'On-leash in town',
  'Mountain town day trip — apple orchards, main street, and nearby trails.',
  'New mountain smells, pie stops, and a big adventure out of the city.',
  'Fall apple season',
  'Moderate',
  null,
  33.0787,
  -116.602,
  true,
  false,
  '/sample-images/mountain.jpg',
  'Julian Dog-Friendly Day Trip — road trip spot',
  'mountain',
  true
),
(
  'lake-cuyamaca',
  'Lake Cuyamaca Recreation Area',
  'Julian',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","lake","trails"}',
  '58 mi',
  'On-leash',
  'Forest lake loop near Julian with cooler mountain air.',
  'Wildlife scents, pine forest, and a true escape from the coast.',
  'Cool-season day trip',
  'Moderate',
  null,
  32.9876,
  -116.5712,
  false,
  false,
  '/sample-images/mountain.jpg',
  'Lake Cuyamaca Recreation Area — road trip spot',
  'mountain',
  true
),
(
  'mount-laguna',
  'Mount Laguna Trail Day Trip',
  'Mount Laguna',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","forest","elevation"}',
  '55 mi',
  'On-leash',
  'High-elevation pine forest trails — snow possible in winter.',
  'Cool air, pine needles underfoot, and big-sky meadow views.',
  'Summer heat escape',
  'High',
  null,
  32.8712,
  -116.4512,
  false,
  false,
  '/sample-images/mountain.jpg',
  'Mount Laguna Trail Day Trip — road trip spot',
  'mountain',
  true
),
(
  'anza-borrego',
  'Anza-Borrego Desert State Park',
  'Borrego Springs',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","desert","wildflowers"}',
  '85 mi',
  'On-leash',
  'Desert day trip — avoid midday heat, bring extra water.',
  'Wild desert smells and wide-open space to explore together.',
  'Spring wildflower season',
  'Moderate',
  null,
  33.2558,
  -116.375,
  true,
  false,
  '/sample-images/trail.jpg',
  'Anza-Borrego Desert State Park — road trip spot',
  'mountain',
  true
),
(
  'idyllwild-day-trip',
  'Idyllwild Mountain Village',
  'Idyllwild',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","mountain","village"}',
  '98 mi',
  'On-leash in town',
  'Alpine village day trip with forest trails and art galleries.',
  'Pine forest trails and a cozy mountain town to sniff around.',
  'Fall weekday',
  'Moderate',
  null,
  33.7412,
  -116.7189,
  false,
  false,
  '/sample-images/trail.jpg',
  'Idyllwild Mountain Village — road trip spot',
  'mountain',
  true
),
(
  'laguna-coast-wilderness',
  'Laguna Coast Wilderness Park',
  'Laguna Beach',
  'Orange County',
  'Trail',
  '{"on-leash","coastal","oc"}',
  '76 mi',
  'On-leash',
  'OC coastal canyon trails — limited shade, bring water.',
  'Dramatic canyon views and a coastal adventure outside SD.',
  'Cool morning',
  'High',
  null,
  33.5812,
  -117.7512,
  false,
  false,
  '/sample-images/trail.jpg',
  'Laguna Coast Wilderness Park — trail spot',
  'forest',
  true
),
(
  'huntington-central-park',
  'Huntington Central Park',
  'Huntington Beach',
  'Orange County',
  'Park',
  '{"on-leash","large","oc"}',
  '90 mi',
  'On-leash',
  'Massive OC park with long flat paths — pair with dog beach visit.',
  'Shaded paths and a full OC day when combined with the beach.',
  'Morning before beach crowds',
  'Moderate',
  null,
  33.7012,
  -117.9912,
  false,
  false,
  '/sample-images/gardens.jpg',
  'Huntington Central Park — park spot',
  'park',
  true
),
(
  'carlsbad-village',
  'Carlsbad Village Walk',
  'Carlsbad',
  'San Diego',
  'Neighborhood',
  '{"on-leash","coastal","shops"}',
  '32 mi',
  'On-leash',
  'Walk State Street and the village grid down toward the pier area.',
  'Beach-town energy, ice cream stops, and ocean breeze.',
  'Sunday morning',
  'Low',
  null,
  33.1581,
  -117.3506,
  false,
  false,
  '/sample-images/park.jpg',
  'Carlsbad Village Walk — neighborhood spot',
  'warm',
  true
),
(
  'oceanside-harbor',
  'Oceanside Harbor Walk',
  'Oceanside',
  'San Diego',
  'Neighborhood',
  '{"on-leash","harbor","flat"}',
  '38 mi',
  'On-leash',
  'Flat harbor promenade with boats, fish smells, and sea lions nearby.',
  'Marine smells and a low-key coastal walk north of SD.',
  'Sunset',
  'Low',
  null,
  33.2012,
  -117.3912,
  false,
  false,
  '/sample-images/neighborhood.jpg',
  'Oceanside Harbor Walk — neighborhood spot',
  'warm',
  true
),
(
  'temecula-patio-day-trip',
  'Temecula Dog-Friendly Patio Day',
  'Temecula',
  'Julian / Mountain',
  'Road trip',
  '{"road-trip","patio","wine-country"}',
  '58 mi',
  'Patio dogs welcome',
  'Old Town Temecula patios and nearby walking paths — verify per venue.',
  'A grown-up day trip with patio time and new country air.',
  'Weekday lunch',
  'Low',
  null,
  33.4936,
  -117.1484,
  false,
  false,
  '/sample-images/road-trip.jpg',
  'Temecula Dog-Friendly Patio Day — road trip spot',
  'mountain',
  true
),
(
  'training-leash-manners',
  'Leash manners loop',
  'Near you',
  'San Diego',
  'Park',
  '{"training","activity","neighborhood"}',
  'Anywhere',
  'On-leash',
  'Short neighborhood loop focused on loose-leash reps.',
  'Tiny training moments can become memories too.',
  'Before dinner',
  'Low',
  null,
  null,
  null,
  false,
  false,
  '/sample-images/gardens.jpg',
  'Leash manners loop — park spot',
  'park',
  true
),
(
  'training-confidence-walk',
  'Confidence walk',
  'Near you',
  'San Diego',
  'Park',
  '{"training","activity","confidence"}',
  'Anywhere',
  'On-leash',
  'Low-pressure route with sniff breaks and praise.',
  'Build brave steps without turning it into a chore.',
  'Quiet morning',
  'Low',
  null,
  null,
  null,
  false,
  false,
  '/sample-images/gardens.jpg',
  'Confidence walk — park spot',
  'park',
  true
),
(
  'training-recall-park',
  'Recall practice at the park',
  'Near you',
  'San Diego',
  'Dog park',
  '{"training","activity","recall"}',
  'Local park',
  'Mixed',
  'Short recall games in a familiar fenced area.',
  'Playful reps that still feel like an outing.',
  'Off-peak hours',
  'Moderate',
  null,
  null,
  null,
  false,
  false,
  '/sample-images/dog-park.jpg',
  'Recall practice at the park — dog park spot',
  'park',
  true
),
(
  'training-calm-cafe',
  'Calm cafe sit',
  'Near you',
  'San Diego',
  'Coffee',
  '{"training","activity","cafe"}',
  'Patio nearby',
  'On-leash',
  'Practice settle duration at a dog-friendly patio.',
  'Real-world calm in a place you already love.',
  'Mid-morning',
  'Low',
  null,
  null,
  null,
  false,
  false,
  '/sample-images/cafe.jpg',
  'Calm cafe sit — coffee spot',
  'urban',
  true
),
(
  'dark-horse-coffee',
  'Dark Horse Coffee Roasters',
  'San Diego',
  'San Diego',
  'Coffee',
  '{"patio","local","north-park"}',
  '3.8 mi',
  'Patio dogs welcome',
  'North Park roastery with sidewalk tables and a relaxed patio vibe.',
  'Patio hangs, new smells, and a short walk through the neighborhood.',
  'Slow weekend morning',
  'Low',
  null,
  32.7398,
  -117.1294,
  false,
  false,
  '/sample-images/cafe.jpg',
  'Dark Horse Coffee Roasters — coffee spot',
  'urban',
  true
),
(
  'training-puppy-basics',
  'Puppy basics session',
  'Near you',
  'San Diego',
  'Park',
  '{"training","activity","puppy"}',
  '15 min',
  'On-leash',
  'Name game, touch, and gentle exposure in a soft loop.',
  'Small wins that add up to a confident pup.',
  'After breakfast',
  'Low',
  null,
  null,
  null,
  false,
  false,
  '/sample-images/gardens.jpg',
  'Puppy basics session — park spot',
  'park',
  true
)
on conflict (id) do update set
  name = excluded.name,
  city = excluded.city,
  region = excluded.region,
  category = excluded.category,
  tags = excluded.tags,
  distance_label = excluded.distance_label,
  leash_info = excluded.leash_info,
  dog_friendly_notes = excluded.dog_friendly_notes,
  why_dogs_love_it = excluded.why_dogs_love_it,
  best_time = excluded.best_time,
  energy_level = excluded.energy_level,
  address_label = excluded.address_label,
  lat = excluded.lat,
  lng = excluded.lng,
  featured = excluded.featured,
  popular_now = excluded.popular_now,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_tone = excluded.image_tone,
  is_active = excluded.is_active;
